spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(hA3FlEdBvKsfgYvrlJtEcyalCit9+Q5lBItpyfYFwmKFZwnDbh2JjEdQ5LRgxRE1KIF0sDMznWSjXoNZJfUjihAEGWz71plXB+ltNLaw/DiCIP4puDjiog==)
            client-secret: ENC(35yohgAE1p0YycOLUyK9UMVr/a10zy0lffhCz/GCE6lI8gaGHXphRBix6ESwIJG5)
            redirect-uri: "http://localhost:9090/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: profile,email

          kakao:
            client-id: ENC(S38TQKrx53Lo6eNXHWKnA78PGgMANzRQxSJEycLMWOCYMnnUHoSwwfFb4Q56/1i/)
            client-secret: ENC(Z6FmpeTowo3d7Dr/uztHGK/7+qODYhkVa7R4wXJUqIunEnlznFcMkp2INe2NyxkM)
            redirect-uri: "http://localhost:9090/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname

          naver:
            client-id: ENC(ERASr3WnLFR96Y7JCzoKYi3zBcvrhmDeOTFC0KJ90QI=)
            client-secret: ENC(edWaW1IYSgZHqwMfznv+QDs3tBn/QbQT)
            redirect-uri: "http://localhost:9090/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email,name
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response