# JavaMailSender 관련 설정
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(SPLoaRQCoef2nJfCA+ZyHVQfJMcrZmC3AH6OWnPgcY4=)
    password: ENC(nnu0j1gqf96ZgOA8VPfCJHGg3/CB8sre5uB7YBtfK1o=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
