spring:
  datasource:
    url: jdbc:mysql://34.135.157.202:3306/tmp?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ENC(RROWyrHl/2wmhc33bTT8K/HqZtP8qb5l)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379