server:
  port: 3000

spring:
  profiles:
    group:
      local: jwt, mail, oauth
  application:
    name: secure-login
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${data.host}/project
    username: ${data.username}
    password: ${data.userpassword}

  mvc:
    web:
      encoding:
        charset: UTF-8
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.jasypt: DEBUG
    org.springframework.security: DEBUG

jasypt:
  encryptor:
    password: ${ENCRYPT_KEY}
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64
