spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip-mate
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379