steps:
  # Docker 이미지를 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tmp-be-app:$COMMIT_SHA'  # Docker 이미지 이름
      - '.'  # Dockerfile이 위치한 디렉토리 (현재 디렉토리)
    id: 'Build Docker image'

  # Docker 이미지를 GCR에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tmp-be-app:$COMMIT_SHA'
    id: 'Push Docker image to GCR'

  # Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tmp-be-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tmp-be-app:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
    id: 'Deploy to Cloud Run'

images:
  - 'gcr.io/$PROJECT_ID/tmp-be-app:$COMMIT_SHA'
