spring:
  datasource:
    url: jdbc:mysql://34.64.149.226:3306/tmp?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: tripmate
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379