steps:
  # Build the container image (skip tests in Gradle build)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'SKIP_TESTS=true'  # Pass argument to Dockerfile to skip tests
      - '-t'
      - 'gcr.io/$PROJECT_ID/tripmate-be:$COMMIT_SHA'
      - '.'
    env:
      - 'data.host=${_DATA_HOST}'
      - 'data.username=${_DATA_USER_NAME}'
      - 'data.userpassword=${_DATA_USER_PASSWORD}'
      - 'ENCRYPT_KEY=${_ENCRYPT_KEY}'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tripmate-be:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tripmate-be'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tripmate-be:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'

images:
  - 'gcr.io/$PROJECT_ID/tripmate-be:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY