tourAPI:
  apiKey: ENC(9dd1GYx12VRzwwANBJL53ymqqLaM4+6QHfoqJWDK2ruAwS+8sFQkkXqwBCgZzgNmR6Rjb8vsL3jYul49FrmGbGZ5igKoJUA6lsowFp9x7FLopXcM69PRkcta/OuKKfww/LoixfoGIU6sPm07P+mwcQ==)
  baseUrl: "https://apis.data.go.kr/B551011/KorService1"
